# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"ConditionalSimNet": "conditionalnet.ipynb",
         "default_image_loader": "loader.ipynb",
         "TripletImageLoader": "loader.ipynb",
         "FILENAMES": "loader.ipynb",
         "resnet18": "run.ipynb",
         "normalize": "run.ipynb",
         "TripletNet": "tripletnet.ipynb"}

modules = ["models/conditionalnet.py",
           "get_data.py",
           "dataset/loader.py",
           "run.py",
           "models/tripletnet.py"]

doc_url = "https://tezike.github.io/tripletnet/"

git_url = "https://github.com/tezike/tripletnet/tree/master/"

def custom_doc_links(name): return None
