# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"resnet18": "conditionalnet.ipynb",
         "ConditionalSimNet": "conditionalnet.ipynb",
         "TripletNet": "tripletnet.ipynb"}

modules = ["models/conditionalnet.py",
           "models/tripletnet.py"]

doc_url = "https://tezike.github.io/tripletnet/"

git_url = "https://github.com/tezike/tripletnet/tree/master/"

def custom_doc_links(name): return None
