# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/get_data.ipynb (unless otherwise specified).

__all__ = []

# Cell
import urllib.request
import os
import os.path
import zipfile

# Cell
if not os.path.exists(os.path.join('data')):
    os.makedirs('data')

# Cell
if os.path.exists(os.path.join('data', 'ut-zap50k-images')):
    pass
else:
    urllib.request.urlretrieve("http://vision.cs.utexas.edu/projects/finegrained/utzap50k/ut-zap50k-images.zip", filename="data/ut-zap50k-imgs.zip")
    print('Downloading Image data...')
    zip_ref = zipfile.ZipFile("data/ut-zap50k-imgs.zip", 'r')
    zip_ref.extractall("data")
    zip_ref.close()
    os.remove("data/ut-zap50k-imgs.zip")

# Cell
if os.path.exists(os.path.join('data', 'tripletlists')):
    pass
else:
    urllib.request.urlretrieve("https://vision.cornell.edu/se3/wp-content/uploads/2019/05/csn_zappos_triplets.zip", filename="data/triplets.zip")
    print('Downloading Triplets list...')
    zip_ref = zipfile.ZipFile("data/triplets.zip", 'r')
    zip_ref.extractall("data")
    zip_ref.close()
    os.remove("data/triplets.zip")