# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/run.ipynb (unless otherwise specified).

__all__ = ['resnet18', 'normalize']

# Cell
import os

import numpy as np

import torch
import torch.nn as nn
import torch.functional as F
import torchvision.models as models
from torchvision import transforms  #TODO: Use albumentations

from .models.conditionalnet import *
from .models.tripletnet import *
from .dataset.loader import *
from tripletnet import get_data

# Cell
resnet18 = models.resnet18(pretrained=True)

# Cell
normalize = transforms.Normalize(mean=[0.485, 0.456, 0.406],
                                     std=[0.229, 0.224, 0.225])